preprocessing:
    sample_ratio: 1.0
    sample_size: null
    oversample_minority: null
    undersample_majority: null
    # Split by sample column to prevent data leakage due to patient-specific attributes.
    split:
        type: hash
        column: sample
        probabilities:
        - 0.7
        - 0.1
        - 0.2
        
input_features:
- name: image_path
  type: image
  encoder: 
      type: resnet
      use_pretrained: true
      trainable: true
      model_variant: 50

output_features:
 - name: er_status_by_ihc
   type: binary
